### ISSUE TITLE
If you require the Claude based on this prompt try to understand and modify the code of an existing project, there will be many error situations.

### ISSUE THREAD

**Issue by kz258852** [richards199999/Thinking-Claude#10]
I have found through practice that the current prompt has good performance for tasks that require starting from scratch. However, when it comes to understanding and modifying code for existing projects, many error situations may arise.

**Comment by richards199999** [comment]
Yes its reasonable, since the instruction a) is probably not well written, b) does not guarantee definite higher performance in all use cases than raw 3.5 Sonnet (new). But you are right about it! it need more iterations, thx for feedback.
