### ISSUE TITLE
Could this be adapted to OpenAI ChatGPT as well?

### ISSUE THREAD

**Issue by junyu-lance-zheng** [richards199999/Thinking-Claude#12]
For the purpose of the internet search capabilities, since that's not yet supported by Claude.

**Comment by tbdavid2019** [comment]
https://chatgpt.com/g/g-AhPpi36JA-olijia-man-si-kao-cot/c/6737efd5-41c0-8012-a6b5-9ac8d308558b
若要用 gpt .. 找找看 gpts 有人有做對應的 prompt

**Comment by richards199999** [comment]
Well, actually I have considered about making one for ChatGPT as an custom GPT (including having a extension for it). However, after some testing, I found this instruction have no good effect on it (GPT-4o's instruction following issue, etc.). Besides, this instruction has exceed 8000 character limit. So yeah, can't and won't make it at least their model and UX get better.
