### ISSUE TITLE
Suggestion to modify the guide of installation

### ISSUE THREAD

**Issue by JoekyRio** [richards199999/Thinking-Claude#13]
Hi Richards, should  the guide of installation of the extensions be modified?
Click "Load unpacked" and select the extension folder ------ >  Click "Load unpacked" and select the chrome folder for chrome or firefox for firefox.

I meet this problem by selecting the extension folder. Aftering having queryed Yuanbao by Tencent, I found I should select the chrome folder, and it works then 
未能成功加载扩展程序文件
D:\**********\Git\Thinking-Claude\extension
错误
清单文件缺失或不可读取
无法加载清单。

**Comment by richards199999** [comment]
Yes you are right. Sorry for that, already changed now!
