### ISSUE TITLE
思维过程以<thinking>... </thinking>的形式呈现

### ISSUE THREAD

**Issue by liuxilai** [richards199999/Thinking-Claude#16]
在一些场景中，当提供的文本过长时，会被作为粘贴文本放入文本框，得到的回复会是如下的格式：

![image](https://github.com/user-attachments/assets/3655c4f7-145f-42a3-bd9b-fc2e9dff959e)

而不是

```thinking

```
这种。

**Comment by richards199999** [comment]
i have observed this circumstance too. however, i think this is because while facing long document some part of its context will lose, which is something i can't fix. but i will try :)

**Comment by mendelg** [comment]
This happend to me once I used the wrong model instructions.
For example, I Used:
v3.5-20241113.md
for the wrong Sonnet model.

**Comment by richards199999** [comment]
i have updated the instructions to v4 (with v4-Lite), you could try them out!

**Comment by liuxilai** [comment]
Thank you for taking the time to look into this issue and provide a solution. I've tried to provide shorter document and I will update the instructions v4. Thanks again for your help and contribution to the project!
