### ISSUE TITLE
Is it possible to make the list of websites that plugins can access available?

### ISSUE THREAD

**Issue by ricklei2777** [richards199999/Thinking-Claude#28]
I am using Claude on other websites such as Poe or some mirror websites, but this plugin has not taken effect.As you can see,The plugin's current list of accessible websites is as follows and cannot be modified:
<img width="942" alt="image" src="https://github.com/user-attachments/assets/6760e02c-50b7-424f-9e28-6dfa124783c6">
The settings pages of some other plugins are shown below, where you can configure them to be available for specific websites:
<img width="1002" alt="image" src="https://github.com/user-attachments/assets/a0e1a2a5-2208-427c-ac94-219402d9f0ee">

**Comment by lumpinif** [comment]
have you tested on all other sites besides the official Claude? I'm afraid it might not be feasible as the content.js script is written based on Claude. It won't work if the element selectors are not working for different sites even if you simply changed the manifest or the configs only.

**Comment by lumpinif** [comment]
I would recommend creating a standalone and designated extension for other websites that you want it to support instead of modifying the main extension.
