### ISSUE TITLE
Only paid users can use this?

### ISSUE THREAD

**Issue by ccsdfsdzxces** [richards199999/Thinking-Claude#32]
**Applying the Thinking Protocol**

1. Copy the latest version in model_instructions folder
2. Start a new Project in Claude.ai
3. Paste the instructions to the Custom Instructions section
4. Claude will now follow the thinking protocol for all subsequent interactions

I can not find "Start a new Project" on claude.ai. Is this only for paid users?

**Comment by lumpinif** [comment]
yes, it;s a paid feature
