### ISSUE TITLE
cursor可以用吗

### ISSUE THREAD

**Issue by sjocnjfjd** [richards199999/Thinking-Claude#33]
我应该怎么把这个thinking claude的promat部署到我的cursor上去呢？

**Comment by lumpinif** [comment]
可以的，在cursor settings->Rules for AI复制粘贴进去。或者在项目根目录创建 `.cusrorules` 存储prompt

**Comment by z1073** [comment]
> 非常感谢，已经可以思考了

怎么样，cursor加了这个提示词效果如何

**Comment by z1073** [comment]
> > > 非常感谢，已经可以思考了
> > 
> > 
> > 怎么样，cursor加了这个提示词效果如何
> 
> 可以思考，就是感觉思考的有点死板，它是按步骤一步一步来思考的

感觉加不加效果差不多，还是不加效率些
