### ISSUE TITLE
Feature Request: Support for perplexity ai

### ISSUE THREAD

**Issue by snust** [richards199999/Thinking-Claude#4]
It would be great if the extension can be used in perplexity!

**Comment by richards199999** [comment]
yes, @samxiaowastaken was right. Complexity is great, you could test that out. And in fact, I have test my instructions on that, the results is good as well!

**Comment by richards199999** [comment]
but i have some plans, will share more!

**Comment by richards199999** [comment]
Already submit a PR for Complexity!: https://github.com/pnd280/complexity/pull/42
