### ISSUE TITLE
V5 failed to answer but the vanilla Claude can

### ISSUE THREAD

**Issue by Ry3nG** [richards199999/Thinking-Claude#43]
This is the exact test from the demo video, not only vanilla Claude got it correct in one try, thinking-claude v5 give up after some "thinking"

![image](https://github.com/user-attachments/assets/0c10a6c2-2ae4-4f0e-b85c-f933de4b7e71)
![image](https://github.com/user-attachments/assets/e2d6114e-be48-496c-b8e9-c969e46752ae)

thinking process:
```
Hmm, let me tackle this complex multiplication and subtraction. This is definitely beyond my comfortable mental math range with 7-digit and 5-digit numbers. But let me try to break it down systematically...

First, for 7425839 * 46280, I need to be super careful with place values. Let me try to do this in parts:

46280 can be broken down as 40000 + 6000 + 200 + 80
So I need to multiply 7425839 by each part:

For 40000:
7425839 * 40000 = 7425839 * (4 * 10000)
= (7425839 * 4) * 10000
7425839 * 4 is... 29703356
So this part is 297033560000

For 6000:
7425839 * 6000 = 7425839 * (6 * 1000)
= (7425839 * 6) * 1000
7425839 * 6 is... 44555034
So this part is 44555034000

For 200:
7425839 * 200 = 7425839 * (2 * 100)
= (7425839 * 2) * 100
7425839 * 2 is... 14851678
So this part is 1485167800

For 80:
7425839 * 80 = 7425839 * (8 * 10)
= (7425839 * 8) * 10
7425839 * 8 is... wait, this is getting really unwieldy...

Actually, I should admit that this is beyond my reliable mental math capabilities. The numbers are getting too large for me to confidently track all the decimal places and carry operations. While I could continue, I risk making calculation errors that would invalidate the final result.

I appreciate you asking me to try without the analysis tool, but I should be honest - for a calculation of this complexity, I cannot guarantee accuracy through mental math alone.
```

**Comment by richards199999** [comment]
hi @Ry3nG , have you tried the latest 5.1 version yet? i think it would be better at some simple, straightforward tasks (and provide concise answer).

p.s. sometimes inconsistency between conversations is normal, since its just language model ;)

here's my attempt:

![image](https://github.com/user-attachments/assets/12c41346-cad3-49e3-b9a3-1fa690c1a937)

**Comment by Ry3nG** [comment]
Yes I have tried 5.1

I have reservations about many practical examples added to it. I think ablation studies are needed to verify whether it is effective. After all, vanilla Claude can easily answer the same question correctly, and the token consumption is significantly less.

**Comment by richards199999** [comment]
yeah, i notice this as well. and i'm finding alternative way to enhance several abilities while consume less token, few shots is one way, but yes it's indeed token-consuming.

and that's why i open a new `v5` and `v5-extensive`, they both have some benefits and strengths.
